repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.4
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: infracost_breakdown
      args:
        - --args= --config-file .infracost-config.yaml 
      verbose: true
    - id: terraform_trivy
      args:
        - --args= --severity CRITICAL
