repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.4
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: infracost_breakdown
      args:
        - --args= --path=./terraform-ecs 
      verbose: true
    - id: infracost_breakdown
      args:
        - --args= --path=./terraform-dns 
      verbose: false
    - id: terraform_trivy
      args:
        - --args= --severity CRITICAL
