name: Deploy terraform from specified folder

on:
  workflow_call:
    inputs:
      tf-folder:
        required: true
        type: string
        description: 'The folder containing Terraform configurations'

jobs:
    deploy-terraform:
        environment: Production
        env:
            TF_VERSION: 1.12.2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
                terraform_version: ${{ env.TF_VERSION }}
          
          - name: Terraform Init
            run: terraform init
            working-directory: ${{ inputs.tf-folder }}

          - name: Terraform Apply
            run: |
                # Plan to review before apply (optional)
                terraform plan -out=tfplan -input=false
                terraform apply -input=false -auto-approve tfplan
            working-directory: ${{ inputs.tf-folder }}