name: Build and Push Docker Image to AWS ECR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      REPOSITORY: fusion
      ECR_REPO_URI: 471230323408.dkr.ecr.us-west-2.amazonaws.com/fusion

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        id: build_image
        run: |
          cd docker  # Remove if Dockerfile is in root
          IMAGE_TAG=${{ github.repository }}:${{ github.sha }}
          docker build -t $ECR_REPO_URI:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Tag Docker Image for ECR
        run: |
          docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:${{ github.sha }}

      - name: Push Docker Image to ECR
        run: |
          docker push $ECR_REPO_URI:${{ github.sha }}
