name: Terraform DESTROY

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.12.2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  
jobs:
  destroy-ecs:
    uses: ./.github/workflows/destroy-tffolder.yml
    secrets: inherit
    with:
      tf-folder: './terraform-ecs'

  delete-ecr-repo:
    environment: Production
    runs-on: ubuntu-latest
    needs: [destroy-ecs]
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Check if ECR repository exists
      id: check-ecr
      run: |
        REPOSITORY_NAME=fusion
        AWS_REGION=us-west-2
        # Check if the repository exists
        if aws ecr describe-repositories --repository-names "$REPOSITORY_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "Repository $REPOSITORY_NAME exists."

            # Get the list of image digests
            IMAGE_DIGESTS=$(aws ecr list-images --repository-name "$REPOSITORY_NAME" --region "$AWS_REGION" --query 'imageIds[*].imageDigest' --output text)

            # Check if there are any images
            if [ -n "$IMAGE_DIGESTS" ]; then
                echo "Images found in the repository. Deleting..."

                # Delete all images in the repository
                aws ecr batch-delete-image --repository-name "$REPOSITORY_NAME" --region "$AWS_REGION" --image-ids "$(aws ecr list-images --repository-name "$REPOSITORY_NAME" --region "$AWS_REGION" --query 'imageIds[*]' --output json)"

                echo "All images in the repository have been deleted."
            else
                echo "No images found in the repository."
            fi
        else
            echo "Repository $REPOSITORY_NAME does not exist."
        fi

  destroy-ecr:
    uses: ./.github/workflows/destroy-tffolder.yml
    secrets: inherit
    needs: [delete-ecr-repo]
    with:
      tf-folder: './terraform-ecr'  

  destroy-ddb:
    uses: ./.github/workflows/destroy-tffolder.yml
    secrets: inherit
    needs: [delete-ecr-repo]
    with:
      tf-folder: './terraform-ddb'  


