name: Terraform Deployment

on:
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'  # Optional, for clarity

    env:
      TF_VERSION: 1.12.2  # specify your terraform version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Initialize and apply Terraform in multiple folders
        run: |
          # Define your folders, e.g., "infra/network" and "infra/apps"
          TERRAFORM_FOLDERS=(
            "terraform-ecs/network"
            # add more folders as needed
          )

          for folder in "${TERRAFORM_FOLDERS[@]}"; do
            echo "Processing folder: $folder"

            cd "$folder"

            # Initialize Terraform
            terraform init -input=false

            # Plan to review before apply (optional)
            terraform plan -out=tfplan -input=false
            
            # If on main branch, run apply, else just validate
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              # Apply only if on main
              terraform apply -input=false -auto-approve tfplan

            cd -  # Return to root
          done
